cpod:
  name: CPODTask
  dataloader:
    batch_size: 8
    num_workers: 8
  dataset:
    name: CPODDataset
    root: ./dataset/cpod
    template_name: ${data_config.template.name}
  gen_kwargs:
    max_new_tokens: 1024
    top_k: 5
    num_beams: 1
    do_sample: False
    use_cache: True
